# Generated by Django 4.1.2 on 2022-10-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_collection_featured_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="featured_product",
        ),
        migrations.AlterField(
            model_name="collection",
            name="featured_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="store.product",
            ),
        ),
    ]
