# Generated by Django 4.1.2 on 2022-10-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_promotion_featured_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
