# Generated by Django 4.1.2 on 2022-10-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="created_at",
            new_name="placed_at",
        ),
    ]
