# Generated by Django 4.1.2 on 2022-10-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_collection_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="placed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
