# Generated by Django 4.1.2 on 2022-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.promotion"
            ),
        ),
    ]
