# Generated by Django 4.1.3 on 2022-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_product_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
    ]
