# Generated by Django 4.1.3 on 2022-11-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="store.collection",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
