# Generated by Django 4.1.3 on 2022-11-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
