# Generated by Django 4.1.3 on 2022-11-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
