# Generated by Django 4.1.3 on 2022-11-29 16:18

import django.core.validators
from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[
                    store.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
    ]
